name: build and deploy

on:
  push:
    branches: [kwonga_mysql]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect & production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          run: |
            cd project_dir
            sudo pm2 kill
            git pull origin kwonga_mysql
            npm i 
            rm .env
            touch .env
            echo ${{ secrets.ENV_FILE }} >> .env
            npm run bilid
            sudo pm2 start dist/main.js
