name: build and deploy

on:
  push:
    branches: [kwonga_mysql]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd Backend
            git pull origin kwonga_mysql
            npm install
            npm run build
            npm run start:prod

            
            
