name: build and deploy

on:
  push:
    branches: [kwonga_mysql]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect & git
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf kwonga_mysql
            git clone https://github.com/M0INDA/Backend/tree/kwonga_mysql.git
            cd kwonga_mysql
            rm .env
            touch .env
            cat << EOF >> .env
            ${{ secrets.ENV_FILE }}
            
            
